CREATE USER normalMember01 WITHOUT LOGIN;
CREATE USER storeClerk01 WITHOUT LOGIN;
CREATE USER DBA01 WITHOUT LOGIN;
CREATE USER Manager01 WITHOUT LOGIN;
CREATE USER normalMember02 WITHOUT LOGIN;
CREATE USER normalMember03 WITHOUT LOGIN;
CREATE USER normalMember04 WITHOUT LOGIN;
CREATE USER normalMember05 WITHOUT LOGIN;