USE master;  
GO  
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'QwErTy12345!@#$%';  
GO  
CREATE CERTIFICATE MyServerCert WITH SUBJECT = 'My DEK Certificate';  
GO  
USE DBS_Assignments;  
GO  
CREATE DATABASE ENCRYPTION KEY  
WITH ALGORITHM = AES_256  
ENCRYPTION BY SERVER CERTIFICATE MyServerCert;  
GO  
ALTER DATABASE DBS_Assignments  
SET ENCRYPTION ON;  
GO  
